#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFactory.Epub
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class TableOfContentsTemplate : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\TableOfContentsTemplate.cshtml"
public CodeFactory.Epub.Models.TableOfContents Model {get;set;} 
        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<html>\r\n<head>\r\n    <title>");


            
            #line 6 "..\..\TableOfContentsTemplate.cshtml"
      Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n</head>\r\n<body>\r\n    <div>\r\n        <h1>\r\n            <b>TABLE OF CONTE" +
"NTS</b>\r\n        </h1>\r\n");


            
            #line 13 "..\..\TableOfContentsTemplate.cshtml"
         foreach (CodeFactory.Epub.Models.ContentItem item in Model.Contents)
        {

            
            #line default
            #line hidden
WriteLiteral("            <b>");


            
            #line 15 "..\..\TableOfContentsTemplate.cshtml"
          Write(item.Category);

            
            #line default
            #line hidden
WriteLiteral("</b>\r\n");



WriteLiteral("            <ul><li><a href=\"");


            
            #line 16 "..\..\TableOfContentsTemplate.cshtml"
                        Write(item.Reference);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 16 "..\..\TableOfContentsTemplate.cshtml"
                                         Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</a></li></ul> \r\n");


            
            #line 17 "..\..\TableOfContentsTemplate.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
